"""empty message

Revision ID: 1db68a2644a1
Revises: 
Create Date: 2021-05-21 21:42:37.248158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db68a2644a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_subheading', sa.String(length=255), nullable=True),
    sa.Column('project_title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_meniu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_meniu_name', sa.String(length=255), nullable=True),
    sa.Column('project_meniu_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('username', sa.VARCHAR(length=50), nullable=True),
    sa.Column('password', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('project_meniu')
    op.drop_table('project_header')
    # ### end Alembic commands ###
