"""empty message

Revision ID: 3cd74a6ef160
Revises: 60c728001757
Create Date: 2021-06-01 12:41:19.940979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd74a6ef160'
down_revision = '60c728001757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientname', sa.String(length=255), nullable=True),
    sa.Column('clientemail', sa.String(length=255), nullable=True),
    sa.Column('clientphoto', sa.String(length=255), nullable=True),
    sa.Column('clientmessage', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
