"""empty message

Revision ID: 40e5c92899a4
Revises: f22a34c1af40
Create Date: 2021-05-27 04:46:03.419298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e5c92899a4'
down_revision = 'f22a34c1af40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('footer_company_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_info', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('footer_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('footer_contact_name', sa.String(length=255), nullable=True),
    sa.Column('footer_contact_icon', sa.String(length=255), nullable=True),
    sa.Column('footer_contact_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('footer_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ft_menu_name', sa.String(length=255), nullable=True),
    sa.Column('ft_menu_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('footer_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer', sa.String(length=255), nullable=True),
    sa.Column('offer_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('footer_social_icon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('footer_si_name', sa.String(length=255), nullable=True),
    sa.Column('footer_si_class', sa.String(length=255), nullable=True),
    sa.Column('footer_si_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('footer_social_icon')
    op.drop_table('footer_offer')
    op.drop_table('footer_menu')
    op.drop_table('footer_contact')
    op.drop_table('footer_company_info')
    # ### end Alembic commands ###
