"""empty message

Revision ID: 4fa960455cbc
Revises: f578e6787f4a
Create Date: 2021-05-25 21:48:01.348691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa960455cbc'
down_revision = 'f578e6787f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('project_info', sa.String(length=255), nullable=True),
    sa.Column('project_link', sa.String(length=255), nullable=True),
    sa.Column('project_link_icon', sa.String(length=255), nullable=True),
    sa.Column('project_img', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_box')
    # ### end Alembic commands ###
