"""empty message

Revision ID: 685e358aac66
Revises: a9386e7cfdfc
Create Date: 2021-05-26 16:24:57.477848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685e358aac66'
down_revision = 'a9386e7cfdfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teambuuton_title', sa.String(length=255), nullable=True),
    sa.Column('teambuuton_icon', sa.String(length=255), nullable=True),
    sa.Column('teambuuton_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_button')
    # ### end Alembic commands ###
