"""empty message

Revision ID: 98b2a504d40b
Revises: 
Create Date: 2021-05-30 12:57:16.659205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b2a504d40b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_heading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_subheading', sa.String(length=255), nullable=True),
    sa.Column('about_heading', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_imgname', sa.String(length=255), nullable=True),
    sa.Column('brand_img', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_heading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_subheding', sa.String(length=255), nullable=True),
    sa.Column('customer_heading', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_heading')
    op.drop_table('brand')
    op.drop_table('about_heading')
    # ### end Alembic commands ###
