"""empty message

Revision ID: a9386e7cfdfc
Revises: aeb8a4749a06
Create Date: 2021-05-26 15:13:49.898565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9386e7cfdfc'
down_revision = 'aeb8a4749a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teammate_img', sa.String(length=255), nullable=True),
    sa.Column('teammate_name', sa.String(length=255), nullable=True),
    sa.Column('teammate_position', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_socil_icon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teammate_icon_name', sa.String(length=255), nullable=True),
    sa.Column('teammate_icon_class', sa.String(length=255), nullable=True),
    sa.Column('teammate_icon_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_socil_icon')
    op.drop_table('team_box')
    # ### end Alembic commands ###
