"""empty message

Revision ID: aeb8a4749a06
Revises: 4fa960455cbc
Create Date: 2021-05-26 00:10:33.426539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb8a4749a06'
down_revision = '4fa960455cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectbtn_title', sa.String(length=255), nullable=True),
    sa.Column('projectbtn_icon', sa.String(length=255), nullable=True),
    sa.Column('projectbtn_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_heading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_subheading', sa.String(length=255), nullable=True),
    sa.Column('team_title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_heading')
    op.drop_table('project_button')
    # ### end Alembic commands ###
