"""empty message

Revision ID: eb460c82c57e
Revises: 1efee5c27941
Create Date: 2021-05-31 16:29:15.044911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb460c82c57e'
down_revision = '1efee5c27941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_desc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_img', sa.String(length=255), nullable=True),
    sa.Column('about_desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('about_heading')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_heading',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('about_subheading', sa.VARCHAR(length=255), nullable=True),
    sa.Column('about_heading', sa.VARCHAR(length=255), nullable=True),
    sa.Column('about_desc', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('about_desc')
    # ### end Alembic commands ###
