"""empty message

Revision ID: f22a34c1af40
Revises: 685e358aac66
Create Date: 2021-05-26 17:54:29.217574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22a34c1af40'
down_revision = '685e358aac66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_status', sa.String(length=255), nullable=True),
    sa.Column('client_desc', sa.String(length=255), nullable=True),
    sa.Column('client_img', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientbutton_title', sa.String(length=255), nullable=True),
    sa.Column('clientbutton_icon', sa.String(length=255), nullable=True),
    sa.Column('clientbutton_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_heading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_subheading', sa.String(length=255), nullable=True),
    sa.Column('client_title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newsbox_title', sa.String(length=255), nullable=True),
    sa.Column('newsbox_desc', sa.String(length=255), nullable=True),
    sa.Column('newsbox_date', sa.String(length=255), nullable=True),
    sa.Column('newsbox_link', sa.String(length=255), nullable=True),
    sa.Column('newsbox_img', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newsbutton_title', sa.String(length=255), nullable=True),
    sa.Column('newsbutton_icon', sa.String(length=255), nullable=True),
    sa.Column('newsbutton_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_heading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_subheading', sa.String(length=255), nullable=True),
    sa.Column('news_title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_heading')
    op.drop_table('news_button')
    op.drop_table('news_box')
    op.drop_table('client_heading')
    op.drop_table('client_button')
    op.drop_table('client_box')
    # ### end Alembic commands ###
