"""empty message

Revision ID: f578e6787f4a
Revises: 1db68a2644a1
Create Date: 2021-05-25 21:26:35.649323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f578e6787f4a'
down_revision = '1db68a2644a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_menu_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('project_meniu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_meniu',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_meniu_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_meniu_url', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('project_menu')
    # ### end Alembic commands ###
